# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Faith and Family 
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Faith and Family Early Learning Center
address_line: 4232 Boonville Rd, Bryan, TX 77802
telephone_number: (979) 774-5300
fax_number: 
company_email: faithandfamilyelc@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13727.867395390593!2d-96.306465!3d30.663062!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x76661c8a0ea2056!2sFaith%20%26%20Family%20Early%20Learning%20Center!5e0!3m2!1sen!2sus!4v1672879741902!5m2!1sen!2sus
# Social Link
facebook_link: http://www.facebook.com/faithandfamilyelc/
twitter_link: 
linkedin_link: 
googleplus_link: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
